# Utterances
# 一个由开源社区构建的评论插件，它提供了一种在博客、文章或任何静态网站上添加互动式评论功能的高效解决方案。
# For more information: https://utteranc.es
utterances:
  # 可选值：true 【启用】 | false 【禁用】
  # Available values: true | false
  enable: false
  # 是否启用加载提示，可选值：true | false
  # Whether to enable loading indicator, Available values: true | false
  loading: true
  # GitHub 仓库所有者 user-name 和 名称 repo-name
  # Github repository owner and name
  repo: user-name/repo-name
  # 指定GitHub issue的匹配规则
  # Available values: pathname | url | title | og:title | `issue number` | `specific term`
  issue_term: pathname
  # 默认主题
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light
  # 深色主题
  # Dark Theme
  dark: github-dark