# Giscus
# 一个利用 GitHub Discussions 实现的评论系统
# For more information: https://giscus.app/
giscus:
  # 可选值：true 【启用】 | false 【禁用】
  # Available values: true | false
  enable: false
  # 是否启用加载提示，可选值：true | false
  # Whether to enable loading indicator, Available values: true | false
  loading: true
  # GitHub 仓库名称，指定评论数据存储在哪个 GitHub 仓库的 Discussions 中。
  # Github repository name
  repo: your-username/your-repo-name
  # GitHub 仓库的唯一ID
  # 调用 GitHub API https://api.github.com/repos/your-username/your-repo-name，
  # 返回的 JSON 中 node_id 字段即为仓库 ID
  # Github repository id
  repo_id: 
  # GitHub Discussions 分类名称。将评论归类到特定讨论板块，方便管理
  # Github discussion category
  category: 
  # Discussions 分类的唯一 ID。 需从 GitHub 获取，与 category 配合使用
  # Github discussion category id
  category_id: 
  # 指定GitHub discussion的匹配规则
  # 可选值： pathname | url | title | og:title | specific
  # Available values: pathname | url | title | og:title | specific
  mapping: pathname
  # 当 mapping 为 specific 时，该值必须配置，如下：
  # - Discussion 的标题包含特定字符串
  # - 特定 discussion 号
  term: 
  # 是否启用严格的标题匹配。当有多个具有相似标题的讨论时，避免由于 GitHub 的模糊搜索方法而导致的不匹配。
  # 可选值: 0（关闭）| 1（启用）
  # Available values: 0 | 1
  strict: 0
  # 是否启用主帖子上的反应。启用后，Discussion 的主帖子上的反应将会显示在评论前
  # 可选值：0（关闭）| 1（启用）
  # Available values: 0 | 1
  reactions_enabled: 1
  # 是否输出 discussion 的元数据。Discussion 的元数据将定期被发送到父页面（被嵌入的页面）。
  # 可选值：0（否）| 1（是）
  # Available values: 0 | 1
  emit_metadata: 0
  # 评论区的主题样式(默认主题)
  # 可选值：light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | preferred_color_scheme | transparent_dark | noborder_light | noborder_dark | noborder_gray | cobalt | purple_dark
  # Available values: light | light_high_contrast | light_protanopia | light_tritanopia | dark | dark_high_contrast | dark_protanopia | dark_tritanopia | dark_dimmed | preferred_color_scheme | transparent_dark | noborder_light | noborder_dark | noborder_gray | cobalt | purple_dark
  theme: light
  # 深色主题
  # Dark Theme
  dark: dark
  # 评论区的语言（界面文本） 如果配置为空，则取 window.navigator.language
  # 可选值：zh-CN | zh-TW | en | es-ES | fr | ru 
  # Available values: zh-CN | zh-TW | en | es-ES | fr | ru 
  lang: 
  # 评论输入框的位置
  # 可选值：
  # bottom-将评论输入框固定在页面的底部（评论列表下方）
  # top-将评论输入框固定在页面的顶部（评论列表上方）
  # Place the comment box above the comments
  input_position: bottom
  # 懒加载评论
  # Load the comments lazily
  data_loading: lazy